name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java with GitHub Packages auth
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: github
          server-username: kattis82
          server-password: ${{ secrets.TOKEN }}
          cache: maven

      - name: Build project
        run: mvn -B clean verify
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_APP_PASSWORD: ${{ secrets.MAIL_APP_PASSWORD }}